// SI/ecommerce-frontend/src/components/Navbar.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm mb-3">
    <div class="container-fluid">
      <RouterLink class="navbar-brand fw-bold" to="/">Shop</RouterLink>

      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#nav"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div id="nav" class="collapse navbar-collapse">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <!-- NO autenticado -->
          <template v-if="!auth.isAuthenticated">
            <li class="nav-item">
              <RouterLink class="nav-link" to="/login">Login</RouterLink>
            </li>
            <li class="nav-item">
              <RouterLink class="nav-link" to="/register">Registro</RouterLink>
            </li>
          </template>

          <!-- SÍ autenticado -->
          <template v-else>
            <li class="nav-item">
              <RouterLink class="nav-link" to="/orders">Mis pedidos</RouterLink>
            </li>
            <li class="nav-item">
              <button class="btn btn-outline-danger ms-lg-3" @click="auth.logout">
                Salir
              </button>
            </li>
          </template>

          <!-- Carrito siempre visible -->
          <li class="nav-item ms-lg-3">
            <RouterLink class="nav-link" to="/cart">
              Carrito <span class="badge bg-secondary">{{ cart.items.length }}</span>
            </RouterLink>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { useAuthStore } from '../store/auth';
import { useCartStore } from '../store/cart';
const auth = useAuthStore();
const cart = useCartStore();
</script>

// frontend/ecommerce/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { CartService } from '../../services/cart.service';
import { Router } from '@angular/router';
import { CartItem } from '../../services/cart.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  isLogged = false;
  cartCount = 0;

  constructor(
    private auth: AuthService,
    private cartService: CartService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.auth.currentUser$.subscribe(u => this.isLogged = !!u);
    this.cartService.items$.subscribe(items =>
      this.cartCount = items.reduce((sum, i) => sum + i.quantity, 0)
    );
  }

  logout(): void {
    this.auth.logout();
    this.router.navigate(['/']);
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" routerLink="/">E-Commerce</a>
    <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item"><a class="nav-link" routerLink="/">Productos</a></li>
        <li class="nav-item" *ngIf="isLogged">
          <a class="nav-link" routerLink="/orders">Historial</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item me-3">
          <a class="nav-link position-relative" routerLink="/cart">
            Carrito
            <span class="badge bg-danger position-absolute top-0 start-100 translate-middle">
              {{ cartCount }}
            </span>
          </a>
        </li>
        <li class="nav-item" *ngIf="!isLogged">
          <a class="nav-link" routerLink="/login">Login</a>
        </li>
        <li class="nav-item" *ngIf="!isLogged">
          <a class="nav-link" routerLink="/register">Registro</a>
        </li>
        <li class="nav-item" *ngIf="isLogged">
          <a class="nav-link" (click)="logout()">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
